### PR TITLE
Add the ability to "archive" questions

### PR DESCRIPTION
**Pull request by razic**
I'd like the ability to archive a question, which would add it to a separate "Archived Questions" section of the home page and make it non-editable (no voting, no adding answers, etc) Then we can archive questions that are no longer relevant.

### CODE REVIEW

**Comment by razic** [comment]
Not ready yet... just getting the pull started. Almost finished.

**Comment by razic** [comment]
@nathansobo there are only two things left to do:
- make the question/answers not editable if in the archived state.
- add route for archived questions so people can bookmark

i'm not exactly sure what the best way to make the questions/answers not editable is. i tried for about an hour but i think i'm doing it incorrectly.

would you mind doing that part? i can probably figure out how to add the route.

**Comment by razic** [comment]
Okay I added the route via this commit: https://github.com/nathansobo/hyperarchy/commit/dd70ff3b21c88cbf4bffb7ce3e2199b94486a6cb

I have good internet now and could screen share with you if you want to pair with me on preventing edits to archived questions.

**Comment by nathansobo** [comment]
Let's screen share to do it on Tuesday. I'm planning on skiing Monday since a big storm is coming. Gotta ski it when it's fresh!

Looking good BTW!

**Comment by razic** [comment]
Alright works for me. can we do it between 9pm - 10pm your time?

**Comment by razic** [comment]
bump

**Comment by nathansobo** [comment]
Shoot. I'm sorry... I dropped the ball on this.

**Comment by nathansobo** [comment]
Maybe I should just make the changes? Time zones are a bitch.

**Comment by razic** [comment]
That would be cool. I'll review the changes so that I know what I should have done. I'm getting ready for bed now :laughing:

**Comment by nathansobo** [comment]
Made some progress on this... It works in the UI, but I haven't finished locking down the server side. We need to prevent rankings from being created / updated for archived questions, and to prevent archived questions from being updated in any way except for unarchiving them.

**Comment by razic** [comment]
@nathansobo Sorry for taking so long with this.

I've locked down the server side for updating questions except unarchiving or destroying.

It appears that the rankings are already not able to be updated/destroyed:

https://github.com/nathansobo/hyperarchy/blob/master/app/models/ranking.rb#L11-L16

I think that takes care of everything and should be ready for prime time. Let me know if you think anything else needs to be added before this can be merged. :+1:

**Comment by nathansobo** [comment]
Thanks @razic! Good to hear from you. How's everything going for you? Still in Thailand?

**Comment by razic** [comment]
@nathansobo Good to hear for you as well :smile:

Things are okay. I still don't have a job yet but I'm interviewing with a couple places.

I'm still in Thailand. It was always my dream to live in a tropical country and to learn a foreign language. I told myself I want to live here for at least a year. :palm_tree::sunny:

How are things with you?

**Comment by razic** [comment]
:+1:

**Pull request merged**
